apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
  namespace: bigdata   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: apache/hive:4.0.0
        ports:
        - containerPort: 9083
        env:
        - name: SERVICE_NAME
          value: "metastore"
        - name: DB_DRIVER
          value: "postgres"
        - name: METASTORE_PORT
          value: "9083"          
        volumeMounts:
        - name: hive-config-volume
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: jar-pvc-volume
          mountPath: /opt/hive/lib/postgres.jar
          subPath: postgres.jar           
      volumes:
      - name: hive-config-volume
        configMap:
          name: hive-config
      - name: jar-pvc-volume
        persistentVolumeClaim:
          claimName: jar-pvc          