apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive
  namespace: bigdata   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiveserver2
  template:
    metadata:
      labels:
        app: hiveserver2
    spec:
      containers:
      - name: hiveserver2
        image: apache/hive:4.0.0
        ports:
        - containerPort: 10000
        - containerPort: 10002
        env:
        - name: SERVICE_NAME
          value: "hiveserver2"
        - name: IS_RESUME
          value: "true"
        volumeMounts:
        - name: hive-config-volume
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: hive-config-volume
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml          
        - name: tez-config-volume
          mountPath: /opt/tez/conf/tez-site.xml
          subPath: tez-site.xml         
      volumes:
      - name: hive-config-volume
        configMap:
          name: hive-config          
      - name: tez-config-volume
        configMap:
          name: tez-config   
