apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata   
spec:
  clusterIP: None
  selector:
    app: hdfs-datanode
  ports:
  - protocol: TCP
    port: 9866
    targetPort: 9866
    name: rpc-port
  - protocol: TCP
    port: 9867
    targetPort: 9867
    name: ipc-port    
  - protocol: TCP
    port: 9864
    targetPort: 9864
    name: http-port        
