apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-resourcemanager
  serviceName: resourcemanager      
  template:
    metadata:
      labels:
        app: hdfs-resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: apache/hadoop:3
        ports:
        - containerPort: 8032 # application Port
        - containerPort: 8030 # scheduler Port
        - containerPort: 8031 # resource-tracker Port
        - containerPort: 8033 # admin Port
        - containerPort: 8088 # Web UI Port
        command: ["yarn", "resourcemanager"]
        volumeMounts:
        - name: resourcemanager-storage
          mountPath: /data/hadoop/yarn/system/rmstore
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
          subPath: yarn-site.xml       
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
          subPath: mapred-site.xml          
      volumes:
      - name: resourcemanager-storage
        persistentVolumeClaim:
          claimName: resourcemanager-pvc
      - name: hadoop-config-volume
        configMap:
          name: hadoop-config         