apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
spec:
  selector:
    app: hdfs-resourcemanager
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
    name: http-port
  - protocol: TCP
    port: 8032
    targetPort: 8032
    name: rpc-port
  - protocol: TCP
    port: 8030
    targetPort: 8030
    name: scheduler-port    