apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-nodemanager
  serviceName: nodemanager      
  template:
    metadata:
      labels: 
        app: hdfs-nodemanager
    spec:
      containers:
      - name: nodemanager
        image: apache/hadoop:
        ports:
        - containerPort: 8042 # Web UI Port        
        command: ["yarn", "nodemanager"]
        volumeMounts:
        - name: nodemanager-storage
          mountPath: /data/hadoop/nm-local-dir
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
          subPath: yarn-site.xml       
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
          subPath: mapred-site.xml          
      volumes:
      - name: nodemanager-storage
        persistentVolumeClaim:
          claimName: nodemanager-pvc
      - name: hadoop-config-volume
        configMap:
          name: hadoop-config              