apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: apache/hive:4.0.0
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: warehouse-volume
          mountPath: /opt/hive/data/warehouse
      volumes:
      - name: warehouse-volume
        persistentVolumeClaim:
          claimName: warehouse-pvc