apiVersion: v1
kind: Service
metadata:
  name: hive
spec:
  selector:
    app: hiveserver2
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
    - protocol: TCP
      port: 10002
      targetPort: 10002
  type: ClusterIP
