apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  namespace: bigdata 
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
          <name>hive.exec.parallel</name>
          <value>true</value>
          <description>Cho phép thực thi song song các tác vụ, giúp tăng tốc độ truy vấn.</description>
      </property>    
      <!-- Cấu hình cho HiveServer2 -->
      <property>
          <name>hive.server2.thrift.port</name>
          <value>10000</value>
          <description>The port on which HiveServer2 will listen for client connections.</description>
      </property>
      <property>
          <name>hive.server2.thrift.bind.host</name>
          <value>0.0.0.0</value>
          <description>The host address the HiveServer2 Thrift service will listen on.</description>
      </property>      
      <!-- Cấu hình cho HiveServer2 WebUI -->
      <property>
          <name>hive.server2.webui.host</name>
          <value>0.0.0.0</value>
          <description>The host address the HiveServer2 WebUI will listen on.</description>
      </property>      
      <property>
          <name>hive.server2.webui.port</name>
          <value>10002</value>
          <description>The port the HiveServer2 WebUI will listen on. This can be set to 0 or a negative integer to disable the web UI.</description>
      </property>    
      #Cấu hình cho Tez Engine
      <property>
        <name>hive.execution.engine</name>
        <value>tez</value>
      </property>
      #Tích hợp với Hive Metastore
      <property>
        <name>metastore.event.db.notification.api.auth</name>
        <value>false</value>
      </property>
      <property>
          <name>hive.compactor.initiator.on</name>
          <value>true</value>
      </property>      
      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://metastore.bigdata.svc.cluster.local:9083</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://citus-master.citus.svc.cluster.local:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>smartconsultor</value>
      </property>
      <property>
        <name> javax.jdo.option.ConnectionPassword</name>
        <value>secret99</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      # warehouse hdfs
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>hdfs://namenode.bigdata.svc.cluster.local:8020/user/hive/warehouse</value>
      </property>
      #Cấu hình YARN cho Tez
      <property>
        <name>hive.tez.container.size</name>
        <value>2048</value>
        <description>The container size for each Tez task, in MB. This should match the YARN container size.</description>
      </property>
      <property>
        <name>hive.tez.java.opts</name>
        <value>-Xmx3072m</value>
        <description>Java options for Tez tasks. Typically, this should be around 75-80% of the container size (hive.tez.container.size).</description>
      </property>
      <property>
        <name>hive.tez.cpu.vcores</name>
        <value>1</value>
        <description>The number of virtual cores allocated for each Tez container.</description>
      </property>
      <property>
        <name>hive.auto.convert.join</name>
        <value>true</value>
        <description>Enable auto map-join conversion, which is especially effective with Tez for small tables.</description>
      </property>
      # Cấu hình Cache
      <property>
        <name>hive.prewarm.enabled</name>
        <value>true</value>
        <description>Enable pre-warming of Tez containers for improved performance.</description>
      </property>
      <property>
        <name>hive.prewarm.numcontainers</name>
        <value>10</value>
        <description>The number of pre-warmed containers when using Tez.</description>
      </property>
      # Cấu hình DAG cho Tez
      <property>
        <name>hive.tez.dynamic.partition.pruning</name>
        <value>true</value>
        <description>Enable dynamic partition pruning for Tez, which helps in reducing unnecessary data reads.</description>
      </property>
      <property>
        <name>hive.optimize.index.filter</name>
        <value>true</value>
        <description>Enable index-based filtering, which can improve performance when working with Tez.</description>
      </property>
      # Cấu hình Thêm cho Hiệu Suất
      <property>
        <name>hive.auto.convert.join.noconditionaltask.size</name>
        <value>10485760</value>
        <description>Size (in bytes) of the smaller table to enable map-side join (20MB in this example).</description>
      </property>
      <property>
        <name>hive.merge.tezfiles</name>
        <value>true</value>
        <description>Enable merging of small Tez files at the end of the job to reduce the number of output files.</description>
      </property>
      <property>
        <name>hive.merge.size.per.task</name>
        <value>256000000</value>
        <description>Size (in bytes) of merged files when using Tez.</description>
      </property>
      <property>
        <name>hive.merge.smallfiles.avgsize</name>
        <value>16000000</value>
        <description>Average file size threshold for triggering merge of small files (16MB in this example).</description>
      </property>
    </configuration>
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode.bigdata.svc.cluster.local:8020</value>
      </property>      
    </configuration>
