apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata   
spec:
  selector:
    app: hdfs-namenode-resourcemanager
  ports:
  - protocol: TCP
    port: 9870
    targetPort: 9870
    name: http-port
  - protocol: TCP
    port: 8020
    targetPort: 8020
    name: rpc-port    