apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: bigdata   
spec:
  selector:
    app: hdfs-namenode-resourcemanager
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
    name: http-port
  - protocol: TCP
    port: 8032
    targetPort: 8032
    name: app-port