apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata   
spec:
  selector:
    app: hdfs-datanode
  ports:
  - protocol: TCP
    port: 9864
    targetPort: 9864
    name: http-port    
    
